const $ = (id) => document.getElementById(id);
const escapeHtml = (v) => String(v ?? "").replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(url, options={}) { const r=await fetch(url,{headers:{"Content-Type":"application/json"},...options}); if(!r.ok) throw new Error((await r.json().catch(()=>({detail:r.statusText}))).detail||r.statusText); return r.json(); }
for (const button of document.querySelectorAll("[data-tab]")) button.addEventListener("click",()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===button)); document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("hidden",x.id!==button.dataset.tab));});
function renderTable(rows, columns){ if(!rows.length) return '<p class="muted">暂无记录</p>'; return `<table><thead><tr>${columns.map(c=>`<th>${escapeHtml(c)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${columns.map(c=>`<td>${c==='status'?`<span class="tag ${escapeHtml(r[c])}">${escapeHtml(r[c])}</span>`:escapeHtml(r[c])}</td>`).join("")}</tr>`).join("")}</tbody></table>`; }
async function refreshJobs(){ try{const rows=await api('/api/raw-pack/jobs'); $('jobList').innerHTML=renderTable(rows,['job_id','stock_code','packs','status','message','output_dir']);}catch(e){$('jobList').textContent=e.message;} }
$('start').onclick=async()=>{try{await api('/api/raw-pack/jobs',{method:'POST',body:JSON.stringify({stock_code:$('jobCode').value,packs:$('jobPacks').value,max_docs:Number($('jobMax').value)})}); await refreshJobs();}catch(e){alert(e.message);}};$('refreshJobs').onclick=refreshJobs;
$('search').onclick=async()=>{try{const code=$('evCode').value;const params=new URLSearchParams({stock_code:code,q:$('evQ').value,status:$('evStatus').value,limit:'500'});const [res,stats]=await Promise.all([api('/api/raw-pack/evidence/search?'+params),api('/api/raw-pack/evidence/stats?stock_code='+encodeURIComponent(code))]);$('metrics').innerHTML=Object.entries({文档:stats.document_count,已下载:stats.downloaded_file_count,已解析:stats.parsed_text_count,权限阻塞:stats.status_counts.PERMISSION_BLOCKED||0,未命中:stats.status_counts.NO_MATCH||0}).map(([k,v])=>`<div class="metric"><span>${k}</span><b>${v}</b></div>`).join(''); const cols=['document_id','status','source_tier','source_organization','document_title','publish_date','source_url','sha256']; $('results').innerHTML=renderTable(res.rows,cols); $('results').querySelectorAll('tbody tr').forEach((tr,i)=>tr.onclick=()=>{$('docCode').value=code;$('docId').value=res.rows[i].document_id;document.querySelector('[data-tab="document"]').click();});}catch(e){$('results').textContent=e.message;}};
$('loadDoc').onclick=async()=>{try{const data=await api(`/api/raw-pack/documents/${encodeURIComponent($('docId').value)}?stock_code=${encodeURIComponent($('docCode').value)}`);$('docMeta').innerHTML=renderTable([data.document],['status','source_tier','source_organization','document_title','source_url','sha256','retrieved_at_utc','entity_match_status','minimum_human_action']);$('docText').textContent=data.text||'无解析文本';}catch(e){$('docText').textContent=e.message;}};
$('loadBlocked').onclick=async()=>{try{const rows=await api('/api/raw-pack/blocked?stock_code='+encodeURIComponent($('blockedCode').value));$('blockedList').innerHTML=renderTable(rows,['source_id','source_organization','access_status','minimum_human_action','impact_if_not_resolved','source_url']);}catch(e){$('blockedList').textContent=e.message;}};
refreshJobs();
