from __future__ import annotations

import argparse
import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

SHA_RE = re.compile(r"^[0-9a-f]{40}$")
DIGEST_RE = re.compile(r"^sha256:[0-9a-f]{64}$")


class TrustedReproductionError(ValueError):
    pass


def _string(value: dict[str, Any], field: str) -> str:
    raw = value.get(field)
    if not isinstance(raw, str) or not raw.strip():
        raise TrustedReproductionError(f"{field} must be a non-empty string")
    return raw.strip()


@dataclass(frozen=True)
class TrustedReproduction:
    status: str
    generated_by: str
    control_commit_sha: str
    task_commit_sha: str
    source_run_id: int
    source_commit_sha: str
    diagnostic_artifact_digest: str
    gate_profile: str
    failure_fingerprint: str
    failure_files: tuple[str, ...]
    observed_at_utc: str

    @classmethod
    def from_mapping(cls, value: dict[str, Any]) -> TrustedReproduction:
        if value.get("schema_version") != 1:
            raise TrustedReproductionError("trusted evidence schema_version must be 1")
        if value.get("status") != "FAIL":
            raise TrustedReproductionError("trusted pre-model gate must reproduce FAIL")
        if value.get("generated_by") != "trusted_pre_model_job":
            raise TrustedReproductionError(
                "trusted evidence must be generated by trusted_pre_model_job"
            )
        control_sha = _string(value, "control_commit_sha")
        task_sha = _string(value, "task_commit_sha")
        source_sha = _string(value, "source_commit_sha")
        for field, sha in (
            ("control_commit_sha", control_sha),
            ("task_commit_sha", task_sha),
            ("source_commit_sha", source_sha),
        ):
            if not SHA_RE.fullmatch(sha):
                raise TrustedReproductionError(f"{field} must be a 40-character SHA")
        source_run_id = value.get("source_run_id")
        if (
            isinstance(source_run_id, bool)
            or not isinstance(source_run_id, int)
            or source_run_id <= 0
        ):
            raise TrustedReproductionError("source_run_id must be positive")
        digest = _string(value, "diagnostic_artifact_digest")
        if not DIGEST_RE.fullmatch(digest):
            raise TrustedReproductionError(
                "diagnostic_artifact_digest must be sha256 plus 64 hex"
            )
        files = value.get("failure_files")
        if not isinstance(files, list) or not 1 <= len(files) <= 5:
            raise TrustedReproductionError(
                "failure_files must contain one to five paths"
            )
        if not all(isinstance(item, str) and item.strip() for item in files):
            raise TrustedReproductionError("failure_files must be non-empty strings")
        return cls(
            status="FAIL",
            generated_by="trusted_pre_model_job",
            control_commit_sha=control_sha,
            task_commit_sha=task_sha,
            source_run_id=source_run_id,
            source_commit_sha=source_sha,
            diagnostic_artifact_digest=digest,
            gate_profile=_string(value, "gate_profile"),
            failure_fingerprint=_string(value, "failure_fingerprint"),
            failure_files=tuple(item.strip() for item in files),
            observed_at_utc=_string(value, "observed_at_utc"),
        )


def load_trusted_reproduction(path: Path) -> TrustedReproduction:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise TrustedReproductionError(
            f"cannot load trusted reproduction: {path}"
        ) from exc
    if not isinstance(value, dict):
        raise TrustedReproductionError("trusted reproduction root must be an object")
    return TrustedReproduction.from_mapping(value)


def build(
    *,
    gate_result: dict[str, Any],
    control_commit_sha: str,
    task_commit_sha: str,
    source_run_id: int,
    source_commit_sha: str,
    diagnostic_artifact_digest: str,
    gate_profile: str,
    observed_at_utc: str,
) -> dict[str, Any]:
    if gate_result.get("status") != "FAIL":
        raise TrustedReproductionError(
            "FAILURE_NOT_REPRODUCIBLE: trusted gate did not fail"
        )
    fingerprint = gate_result.get("failure_fingerprint")
    files = gate_result.get("failure_files")
    value = {
        "schema_version": 1,
        "status": "FAIL",
        "generated_by": "trusted_pre_model_job",
        "control_commit_sha": control_commit_sha,
        "task_commit_sha": task_commit_sha,
        "source_run_id": source_run_id,
        "source_commit_sha": source_commit_sha,
        "diagnostic_artifact_digest": diagnostic_artifact_digest,
        "gate_profile": gate_profile,
        "failure_fingerprint": fingerprint,
        "failure_files": files,
        "observed_at_utc": observed_at_utc,
    }
    TrustedReproduction.from_mapping(value)
    return value


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--gate-result", type=Path, required=True)
    parser.add_argument("--control-commit-sha", required=True)
    parser.add_argument("--task-commit-sha", required=True)
    parser.add_argument("--source-run-id", type=int, required=True)
    parser.add_argument("--source-commit-sha", required=True)
    parser.add_argument("--artifact-digest", required=True)
    parser.add_argument("--gate-profile", required=True)
    parser.add_argument("--observed-at-utc", required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    gate_result = json.loads(args.gate_result.read_text(encoding="utf-8"))
    if not isinstance(gate_result, dict):
        raise SystemExit("gate result root must be an object")
    value = build(
        gate_result=gate_result,
        control_commit_sha=args.control_commit_sha,
        task_commit_sha=args.task_commit_sha,
        source_run_id=args.source_run_id,
        source_commit_sha=args.source_commit_sha,
        diagnostic_artifact_digest=args.artifact_digest,
        gate_profile=args.gate_profile,
        observed_at_utc=args.observed_at_utc,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(value, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(asdict(TrustedReproduction.from_mapping(value)), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
